app = "websocket1"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
