app = "websocket1"

[build]
  dockerfile = "Dockerfile"

  [build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["paketo-buildpacks/python"]
  environment = { BP_CPYTHON_VERSION = "3.10" }

[env]
  PORT = "5000"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true
